### PR TITLE
Problem 74 : Implementation of Cosine Similarity

### LINKED ISSUE #131: New Problem : Cosine Similarity
Problem to implement cosine similartity.
The learn tab includes use cases and pitfalls. 
In the future probably could add the problem to implement other distance metrics as well for example: Chebyshev distance

### PR DESCRIPTION
**Pull request by saitiger**
Solution and introduction for cosine similarity.

Resolves #131

### CODE REVIEW

**Comment by moe18** [comment]
would you be able to make this problem number 76

**Comment by saitiger** [comment]
Renamed to problem 76, and have pushed  a new PR for the same

**Comment by moe18** [comment]
@saitiger would you be able to add a linear algebra implementation of cosine similarity?

**Comment by saitiger** [comment]
Yes, I can do that. I need to clarify one thing. Is this going to be a separate question? If so, I will create a new branch and add the solution there.

**Comment by moe18** [comment]
No this will be part of the same question, just a different way to solve it

**Pull request closed without merging**
