### PR TITLE
add vector dot product

### PR DESCRIPTION
**Pull request by rittik9**
solves https://github.com/Open-Deep-ML/DML-OpenProblem/issues/185

### CODE REVIEW

**Comment by moe18** [comment]
For this PR its fine, just moving forward

**Comment by moe18** [comment]
it should be one PR for each problem, make a pull from main and then add a new problem then make a PR

**Comment by rittik9** [comment]
problem no?

**Comment by rittik9** [comment]
It's fixed now, pr with only vector dot product

**Comment by moe18** [comment]
this is question 83

**Comment by rittik9** [comment]
@moe18 done. added prob. no.

**Review by moe18 — APPROVED** [review]

**Pull request merged**
